// Generated by CoffeeScript 1.6.2
(function() {
  window.options = function($scope, $timeout) {
    $scope.data = angular.copy(localStorage);
    $scope.save = function(connect) {
      angular.extend(localStorage, $scope.data);
      $scope.saved = true;
      $timeout(function() {
        return $scope.saved = false;
      }, 2000);
      if (connect) {
        return $scope.connect();
      }
    };
    $scope.clear = function() {
      $scope.data = {
        username: '',
        password: ''
      };
      $scope.save();
      return $scope.disconnect();
    };
    $scope.connect = function() {
      var github;

      $scope.error = false;
      github = new Github({
        username: localStorage.username,
        password: localStorage.password,
        auth: "basic"
      });
      return github.getUser().repos(function(err) {
        if (err) {
          return $scope.error = JSON.parse(err.request.response).message;
        } else {
          return chrome.extension.sendRequest("connect");
        }
      });
    };
    return $scope.disconnect = function() {
      return chrome.extension.sendRequest("disconnect");
    };
  };

}).call(this);
