name: Package Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Package extension
      run: zip -r extension.zip . -x ".git/*" ".github/*"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension
        path: extension.zip
